EngineUserSettings {
 VideoUserSettings VideoUserSettings {
  WindowMode BORDERLESS
  ScreenWidth 2560
  ScreenHeight 1440
  ResolutionScale 1
  FsrEnabled 0
  FsrSharpening 0
  CasSharpening 0
  Fsaa NONE
  DistantShadowsQuality MEDIUM
  EnvironmentQuality HIGH
  Atoc NONE
  Gamma 0
  Contrast 0
  Brightness 0
 }
 DisplayUserSettings DisplayUserSettings {
  PPQuality PPEffectsSettings {
   HBAO 1
   GodRays 0
   HDR 0
   SSDO 1
   SSR 1
   UnderWater 1
   PPAA 2
   Rain 1
  }
 }
 GraphicsQualitySettings GraphicsQualitySettings {
  ObjectDrawDistanceScale Ultra
 }
 PipelineUserSettings PipelineUserSettings {
  ShadowQuality Medium
  LightShadow 2
  LightLevel 2
  Reflections 0
 }
 ResourceManagerUserSettings ResourceManagerUserSettings {
  TextureDetail 0
  GeometricDetail 2
 }
 GrassMaterialSettings GrassMaterialSettings {
  Distance 175
  Lod 3
  Quality 0
 }
 TerrainGenMaterialSettings TerrainGenMaterialSettings {
  Detail 3
  SoftAlpha 1
  DetailDistance 1
  GeometryLevel 0
 }
 MaterialSystemUserSettings MaterialSystemUserSettings {
  TextureFilter 2
  MaxAniso 4
 }
 WaterPoolMaterialSettings WaterPoolMaterialSettings {
  Detail 1
 }
}
